### ISSUE TITLE
about encrypt

### ISSUE THREAD

**Issue by kurisucat** [leohearts/AlternativeUnlockXposed#1]
Readme mentioned "And by the way it also works before your first unlock after reboot."

If device is encrypted, system may reqiure password to decrypt such as /data. 

In this case, how do this module work?

**Comment by kurisucat** [comment]
so when i enter "real password", in first unlock and "real password" different in set before in settings, does system unlock or require enter the password set in settings?

**Comment by kurisucat** [comment]
i think system require password to decrypt. so i don't know when i enter the fake or real password at first unlock, what kind of behavior will they show? ( i think when i enter fake password it will still do action and won't unlock the screen )

i didn't use this module on my phone. sorry about that.

**Comment by leohearts** [comment]
When fake password provided, this module detects the input and replace it with the real password. So providing fake password and real password both unlocks , regardless of it's the first unlock or not.On Feb 7, 2024 9:40 PM, Kurisu Cat ***@***.***> wrote:
so when i enter "real password", in first unlock and "real password" different in set before in settings, does system unlock or require enter the password set in settings?

**Comment by leohearts** [comment]
> i think system require password to decrypt. so i don't know when i enter the fake or real password at first unlock, what kind of behavior will they show? ( i think when i enter fake password it will still do action and won't unlock the screen )
> 
> i didn't use this module on my phone. sorry about that.

Fake password also unlocks, even before decryption. And since it will be replaced with the real password, it can also successfully decrypt the phone.

**Comment by kurisucat** [comment]
> > i think system require password to decrypt. so i don't know when i enter the fake or real password at first unlock, what kind of behavior will they show? ( i think when i enter fake password it will still do action and won't unlock the screen )
> > i didn't use this module on my phone. sorry about that.
> 
> Fake password also unlocks, even before decryption. And since it will be replaced with the real password, it can also successfully decrypt the phone.

Thanks! So I understand how does the module work.

I afraid real password is not encrypt stored and easy to evidence collection.

Can I leave the "real password" empty?

**Comment by leohearts** [comment]
> > > i think system require password to decrypt. so i don't know when i enter the fake or real password at first unlock, what kind of behavior will they show? ( i think when i enter fake password it will still do action and won't unlock the screen )
> > > i didn't use this module on my phone. sorry about that.
> > 
> > 
> > Fake password also unlocks, even before decryption. And since it will be replaced with the real password, it can also successfully decrypt the phone.
> 
> Thanks! So I understand how does the module work.
> 
> I afraid real password is not encrypt stored and easy to evidence collection.
> 
> Can I leave the "real password" empty?

Yes you can. You'll not be able to unlock with the fake password, but trigger command will also be executed.

Password is stored unencrypted in /data/local/tmp/*****.properties and every process can read it . (But since app can't list /data/local/tmp, they should not know it's existence)

We may need a better method to store the password.

**Comment by kurisucat** [comment]
Thanks for your answers!
