### ISSUE TITLE
Can you add support to android 13? I have some ideias with this module. I'd like to test to improve my phone security.

### ISSUE THREAD

**Issue by baianohak** [leohearts/AlternativeUnlockXposed#4]

**Comment by baianohak** [comment]
> Yep I'd like to. Does it work on 13 now? If not, I'll try it on a new Android 13 phone. (As all my dev is 14)
>
>
— Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: *** @ ***. * * >

Unfortunately it doesn't seem to work on Android - - 13.

**Comment by leohearts** [comment]
> > Yep I'd like to. Does it work on 13 now? If not, I'll try it on a new Android 13 phone. (As all my dev is 14)
> 
> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: *** @ ***. * * >
> 
> Unfortunately it doesn't seem to work on Android - - 13.

How did you test that ? It works well on an Android 13 avd .

![Screenshot_20240409_192209](https://github.com/leohearts/AlternativeUnlockXposed/assets/24632029/b59eab78-4ad5-4463-ae74-f401339d12a3)

**Comment by leohearts** [comment]
> I'm crdroid 13 it crashes. It does not even open.

Do you have magisk and LSPosed ? It'll be pretty helpful if you can paste some logcat here.

**Comment by baianohak** [comment]
Yes, I do have Kernel SU and Lsposed. How can I provide the logs?

**Comment by baianohak** [comment]
Key bro, I'm sorry. I got a log here if ask for root permission, I thought it was only a Xposed modules. I given the permission and it opened my, can you answer me how to I set a command, I tried but it's not working ![Screenshot_20240411-124431_AlternativeUnlockXposed.png](https://github.com/leohearts/AlternativeUnlockXposed/assets/99616052/bee1cbbe-7cbf-48cf-8939-e5abb7ae32bf)

**Comment by baianohak** [comment]
Bro, how can I set the command? It's not working, first line is sudo and next line is the command? 

sudo

am broadcast -a com.jozein.xedgepro.PERFORM -e data 63640283020FF949B80252265202

**Comment by baianohak** [comment]
I finally made it works. Do you know a ola module called NoLockscreenWallpaper? It's on GitHub, it would be good if you can implement a funcion that have there.

**Comment by leohearts** [comment]
Unfortunately this may not be what this app should do. Maybe you can use them together?On Apr 14, 2024 3:16 AM, baianohak ***@***.***> wrote:
I finally made it works. Do you know a ola module called NoLockscreenWallpaper? It's on GitHub, it would be good if you can implement a funcion that have there.

**Comment by baianohak** [comment]
You module is the final touch of a setting that I created to improving security on my phone. I do some modifications on Android to get it better. I really appreciated your work. Stay well. Hugs bro 🙂

**Comment by leohearts** [comment]
Thanks 💖 Glad to see this helps ppl
