### ISSUE TITLE
Themed/Monochrome App Icon

### ISSUE THREAD

**Issue by NielSync** [leohearts/AlternativeUnlockXposed#5]
![Screenshot_20240629-193107.jpg](https://github.com/leohearts/AlternativeUnlockXposed/assets/20804647/4f624676-876f-4dec-8c95-9f14ca46bf57)

**Comment by leohearts** [comment]
Added in 1.1🎉
Future ideas and suggestions welcome!

**Comment by leohearts** [comment]
![image](https://github.com/user-attachments/assets/5f7fab5a-e92a-4747-bd17-aef7d1aa97b7)
lgtm

**Comment by leohearts** [comment]
https://github.com/leohearts/AlternativeUnlockXposed/releases/tag/1.1v2
