### ISSUE TITLE
make the real password field hidden

### ISSUE THREAD

**Issue by MeltyObserver** [leohearts/AlternativeUnlockXposed#8]
what the title says. instead of showing the real password replace it with `xxxxx` for extra security

**Comment by leohearts** [comment]
Good idea. Could prevent shoulder surfing .On Sep 20, 2024 2:01 PM, Melty Observer ***@***.***> wrote:
what the title says. instead of showing the real password replace it with xxxxx for extra security

**Comment by leohearts** [comment]
https://github.com/leohearts/AlternativeUnlockXposed/releases/tag/1.5
